[platformio]
description = AI_Robot Voice_Buddy — ESP32-S3 语音助手

[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = color

upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0


; ========= N16R8 16MB Flash + 8MB OPI PSRAM 配置（qio_opi，子项目实机验证过） =========
board_build.partitions = partitions16.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
build_flags = -DBOARD_HAS_PSRAM
; ==================================================================================

lib_deps =
    bblanchon/ArduinoJson@^6.21.3
    gilmaimon/ArduinoWebsockets@^0.5.3
    me-no-dev/AsyncTCP@^1.1.1
    esphome/ESP32-audioI2S@^2.0.7
    esphome/ESPAsyncWebServer-esphome@^3.2.2
    olikraus/U8g2@^2.35.14
