[platformio]
description = AI_Robot Voice_Buddy — ESP32-S3 语音玩伴

[env:esp32-s3-devkitc-1]
#espressif32 6.5.0 库版本锁定：不要删掉@6.5.0，升级平台包后 OPI PSRAM、audioI2S 可能出现不兼容。
platform = espressif32 @ 6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = color

#Windows 开发环境要改成 upload_port = COMx。WSL里USB串口不稳定、找不到 ACM0：需要usbipd挂载USB设备；
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0


; ========= N16R8 16MB Flash + 8MB OPI PSRAM 配置（qio_opi，子项目实机验证过） =========
#修改partitions16.csv之后，一定要执行 pio run -t fullclean，否则旧分区缓存残留，烧录后启动异常
board_build.partitions = partitions16.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
build_flags = -DBOARD_HAS_PSRAM
; ==================================================================================

lib_deps =
    bblanchon/ArduinoJson@^6.21.3
    gilmaimon/ArduinoWebsockets@^0.5.3
    me-no-dev/AsyncTCP@^1.1.1
    esphome/ESP32-audioI2S@^2.0.7
    esphome/ESPAsyncWebServer-esphome@^3.2.2
    olikraus/U8g2@^2.35.14
